# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
username: Brandon Spruth
title: WebBreaker
email: webmaster@webbreaker.io
description: >- # this means to ignore newlines until "baseurl:"
  WebBreaker is an open source Dynamic Application Security Test Orchestration (DASTO) client, enabling development
  teams to create pipelines for security testing, or build, execute and automate functional security tests, from
  WebInspect, Fortify SSC, and ThreadFix.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http" # the base hostname & protocol for your site, e.g. http://example.com
github_url: https://github.com/target/webbreaker
youtube_url: https://www.youtube.com/channel/UCUNc7fgGUcoATi0Wfpl0AoA
guide_url: https://target.github.com/webbreaker

# Download URLs
high_sierra_download_url: https://github.com/target/webbreaker/releases/download/v2.2.0/webbreaker-osx-high-sierra
sierra_download_url: https://github.com/target/webbreaker/releases/download/v2.2.0/webbreaker-osx-sierra
centos_download_url: https://bintray.com/webbreaker/webbreaker-cli/webbreaker/_latestVersion
fedora_download_url: https://bintray.com/webbreaker/webbreaker-cli/webbreaker/_latestVersion
redhat_download_url: https://bintray.com/webbreaker/webbreaker-cli/webbreaker/_latestVersion
windows10_download_url: https://github.com/target/webbreaker/releases/download/v2.2.0/webbreaker-win-10.exe

# Build settings
markdown: kramdown
theme: minima

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
